name: Checkov RBAC Validation

on:
  push:
  pull_request:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run RBAC policy
        run: |
          checkov \
            -d terraform \
            --framework terraform \
            --external-checks-dir checkov \
            --check CKV2_CUSTOM_AZURE_001
