name: Terraform Security Validation

on:
  push:
  pull_request:

jobs:
  security-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install pyyaml checkov

      - name: Validate RBAC matrix
        run: |
          python scripts/validate-rbac.py

      #- name: Run Checkov
       # run: |
        #  checkov \
         #   -d terraform \
          #  --framework terraform